### ISSUE TITLE
Use paremeter filter in controllers

### ISSUE THREAD

**Issue by xprazak2** [oamg/foreman_leapp#12]
foreman_leapp should use parameter filters in controllers to permit strong params. This will permit parameters in controller and will avoid the need to call `permit` in lower layers, such as is currently done in `PreupgradeReport`.

**Comment by stejskalleos** [comment]
Do we need it since we don't create or update any models via controllers?

* `api/v2/PreupgradeReportsController` just have `GET index & show` endpoints
* `PreupgradeReportsController` same, only one `GET index`

**Comment by xprazak2** [comment]
I think we can close, thanks.
