### ISSUE TITLE
Add index action to PreupgradeReportsController

### ISSUE THREAD

**Issue by xprazak2** [oamg/foreman_leapp#16]
It should be possible to list all preupgrade reports using API. The index endpoint should support search as well.

**Comment by ares** [comment]
@stejskalleos could you please take a look at this when you have a moment? we probably need this sooner than for CLI in order to allow frontend to search/filter the table.

**Comment by stejskalleos** [comment]
Yop, I'll look into it. Should it be just in `ApiController` or do we want to have also page in frontend UI?

**Comment by ares** [comment]
I'd say just API since the UI part is handled as part of the job invocation detail page.

**Comment by stejskalleos** [comment]
https://github.com/oamg/foreman_leapp/pull/27

**Comment by xprazak2** [comment]
Fixed by #27, thanks!
