### ISSUE TITLE
Show more attributes in preupgrade report entry list

### ISSUE THREAD

**Issue by xprazak2** [oamg/foreman_leapp#21]
Currently, list item for preupgrade report entry shows only `title` and `severity`. We should dispaly additional info as well, namely:

* whether the issue prevents upgrade
* whether the issue has remediation
* host where this was detected

We should also get a look that is as close to the following as possible:
https://raw.githubusercontent.com/cockpit-project/cockpit-design/2666713868646a73460407c82aadc2964e5d600e/inplace-upgrades/upgrade-report-alt.png

**Comment by fellipeh** [comment]
Added on these PR:
https://github.com/oamg/foreman_leapp/pull/37
