### ISSUE TITLE
Allow user to select preupgrade report entries to fix

### ISSUE THREAD

**Issue by xprazak2** [oamg/foreman_leapp#32]
List item for report entry with a remediation should contain a checkbox and user should be able to check individual entries and then click 'Fix selected' button to fix the entries that were selected.

We probably want a 'Check all' button as well. This would make 'Fix all' button redundant, so the new flow would be 'Check all', then 'Fix selected' to achive the same as 'Fix all' button.

Depends on #24.

**Comment by adamruzicka** [comment]
#37 was mergeed, closing.
