### ISSUE TITLE
When the leap output contains error, nothing meaningul is shown to the user

### ISSUE THREAD

**Issue by ares** [oamg/foreman_leapp#49]
Make a type in the json output or some syntax issue, run the job. The job fails (expected) however the "Leapp preupgrade report" is empty and does not show any meaningul error message.

**Comment by ares** [comment]
It may be something on my side too since the tab content isn't populated until I reload the page. I found the message in foreman task detail page.

**Comment by stejskalleos** [comment]
@ares Is it still valid or can we close the issue?

**Comment by stejskalleos** [comment]
When job is finished (state don't matter) `Leapp preupgrade report` tab is automatically reloaded.

In case of error user can see this:
![leapp_error](https://user-images.githubusercontent.com/59385976/86091774-bf02e280-baac-11ea-94e7-ab9be1df54b3.png)

**Tested scenarios:**
- Invalid `leapp-report.json` file
- Missing `leapp-report.json` file
- Leapp failure (running it with invalid parameter: `leapp blablabla`)


When there are hosts with status `success` and hosts with status `failed`, we will show reports for all hosts with `success` status  without any other alert about failed hosts. It's not best UX - it has been discussed on Leapp meeting where we decided to keep it as it is and wait for the feedback from first users.

I'm closing the issue, as it has been already solved
