### ISSUE TITLE
Need a "select all" link

### ISSUE THREAD

**Issue by ares** [oamg/foreman_leapp#65]
For big number of reports, it's impossible to click every single checkbox. We should have "check all" link that would

1) select all if at least one checkbox is unselected
2) unselect all if all checkboxes are selected
3) both 1 and 2 works on all pages, not just the one I'm at

This may be just a checkbox in header row, that should be added by https://github.com/oamg/foreman_leapp/issues/20

**Comment by xprazak2** [comment]
Will be fixed by #70

**Comment by stejskalleos** [comment]
Closing issue, solved in #70
