### ISSUE TITLE
Inhibited upgrade

### ISSUE THREAD

**Issue by stejskalleos** [oamg/foreman_leapp#73]
When Leapp's inhibitor detect some issue, task `leapp preupgrade` will generate output as usual but exit with status 1, which means failed job in foreman. But preupgrade report in `/var/log/leapp/leapp-report.json` is still generated and could be used.

See result from job:
```
2219:============================================================
2220:                     UPGRADE INHIBITED                      
2221:============================================================
2222:
2223:Upgrade has been inhibited due to the following problems:
2224:    1. Inhibitor: A YUM/DNF repository defined multiple times
2225:Consult the pre-upgrade report for details and possible remediation.
2226:
2227:============================================================
2228:                     UPGRADE INHIBITED                      
2229:============================================================
2230:
2231:
2232:Debug output written to /var/log/leapp/leapp-preupgrade.log
2233:
2234:============================================================
2235:                           REPORT                           
2236:============================================================
2237:
2238:A report has been generated at /var/log/leapp/leapp-report.json
2239:A report has been generated at /var/log/leapp/leapp-report.txt
2240:
2241:===========================================================
2242:                       END OF REPORT                        
2243:============================================================
2244:
2245:Answerfile has been generated at /var/log/leapp/answerfile
2246:Exit status: 1
```
**How to reproduce**
* running Leapp DEV RHEL VM
* Register RHEL and attach it to the pool
* Do not disable variables `LEAPP_DEVEL_SKIP_RHSM` & `LEAPP_UNSUPPORTED`
* Run `leapp preupgrade`

Question is, how do we want to handle this case? The same way how we do now or add some conditions and change the behavior for this case with inhibited upgrade.

**Comment by adamruzicka** [comment]
Is it mentioned somewhere in the report that the upgrade would be inhibited?

**Comment by stejskalleos** [comment]
Yop, it is:
```
    {
      "hostname": "leapp-20200428104609", 
      "severity": "medium", 
      "tags": [
        "repository"
      ], 
      "timeStamp": "2020-04-28T11:58:12.182890Z", 
      "title": "A YUM/DNF repository defined multiple times", 
      "detail": {
        "remediations": [
          {
            "type": "hint", 
            "context": "Remove the duplicate repository definitions or change repoids of conflicting repositories on the system to prevent the conflict."
          }
        ]
      }, 
      "actor": "target_userspace_creator", 
      "summary": "The following repositories are defined multiple times inside the \"upgrade\" container:\n    - rhel-7-server-rpms\n    - rhel-7-server-optional-rpms\n    - rhel-7-server-extras-rpms", 
      "audience": "sysadmin", 
      "flags": [
        "inhibitor"
      ], 
      "id": "d33af1f40b281b697f1a548b1ed9aa4c5dffe0a7ed173b9264288addb001b412"
    }
```
Funny thing is `"severity": "medium"`.

**Comment by stejskalleos** [comment]
Fix could be easy:

```
# Before
leapp preupgrade
[ $? -eq 0 ]  || exit 1

# After:
rm -f /var/log/leapp/leapp-report.json
leapp preupgrade
```
We don't care about status of preupgrade command, we just remove `leapp-report.json` and if there won't be any new `leapp-report.json` (that means `leapp preupgrade` failed) foreman job will fail as usual.

**Comment by ares** [comment]
if I understand that correctly, it may be a good idea to rm the report anyway so we always get fresh data

and I agree, inhibitors should be marked more significantly in the UI, they should be on top of the list by default and ideally we could also filter by that attribute

**Comment by stejskalleos** [comment]
> it may be a good idea to rm the report anyway so we always get fresh data
Yop, added in https://github.com/oamg/foreman_leapp/pull/71

> inhibitors should be marked more significantly in the UI, they should be on top of the list by default and ideally we could also filter by that attribute
@xprazak2

**Comment by xprazak2** [comment]
Ok, I'll make them more visible.
