### ISSUE TITLE
UI does not show all preupgrade reports

### ISSUE THREAD

**Issue by adamruzicka** [oamg/foreman_leapp#80]
I ran a preupgrade job against 600-ish hosts. When I go to the preupgrade reports tab, I can see 300 preupgrade report entries, spread across 15 pages. However if I add `params[:per_page] = 1000` to the controller before the records get retrieved, the UI will show 9210 preupgrade report entries, spread across 461 pages.

Apparently the controller returns paginated results, but the UI expects to get everything at once.

**Comment by stejskalleos** [comment]
Fixed in https://github.com/oamg/foreman_leapp/pull/82

**Comment by adamruzicka** [comment]
#82 was closed in favor of #81
