### ISSUE TITLE
Preupgrade report entries' text and icons are not vertically centered

### ISSUE THREAD

**Issue by adamruzicka** [oamg/foreman_leapp#84]
I'd expect the title and icons to be aligned vertically to the center of the row, same as the checkbox

![image](https://user-images.githubusercontent.com/7326770/81338336-c27d7d00-90ac-11ea-85a9-8c2b93da9394.png)

**Comment by stejskalleos** [comment]
Moved to https://projects.theforeman.org/issues/29922.
