### ISSUE TITLE
Schedule job - Upgrade action is in different category than other Leapp actions

### ISSUE THREAD

**Issue by stejskalleos** [oamg/foreman_leapp#89]
Upgrade action is in _Ansible Playbook_ category, but other Leapp actions are in _Leapp_ category. This can be confusing for users.

**Comment by stejskalleos** [comment]
I'm not sure about the best solution for this issue. If I change category of `upgrade` template to `Leapp`, form for new job invocation will show job template for both providers (Leapp & Ansible), like this:
![Screenshot_20200522_141029](https://user-images.githubusercontent.com/59385976/82666515-60894f80-9c36-11ea-89c0-abd042e6c428.png)

@ares, @adamruzicka  any ideas how to solve the issue?

**Comment by adamruzicka** [comment]
There's no easy way out I'm afraid. This has been a thorn in our side for a long time already and I'd like to see it gone, but that's not a 5 minute fix. As I see it, we have three options:

1) Leave things the way they are, get rid of multiple providers in form in the near future (post 6.8), change the category afterwards.
2) Rewrite the other two templates in ansible. Ansible handles reboot survival nicely, rewriting the others to ansible is possibly less work than implementing reboot survival ourselves. This however wouldn't be completely hassle free as we would have to parse the output of ansible to extract the report from it.
3) Rewrite the upgrade template to shell and handle reboot survival ourselves.

**Comment by stejskalleos** [comment]
Will be done in https://github.com/oamg/foreman_leapp/issues/93
