### ISSUE TITLE
Include reboot can cause indentation issue and cause job to fail

### ISSUE THREAD

**Issue by ares** [oamg/foreman_leapp#92]

**Comment by stejskalleos** [comment]
Formatting was not the issue, but the version of Ansible was the problem.
Ansible `reboot` task was introduced in 2.7 version, but Ansible installed on host was 2.4 -  Unmaintained & end of life version. After upgrade of Ansible job doesn't fail anymore.

**Comment by adamruzicka** [comment]
For the sake of completeness, 6.7 docs suggest enabling `rhel-7-server-ansible-2.8-rpms` repository so we can safely assume users should be using `>=2.8.0`. In upstream epel currently provides `2.9.9` so we should be safe there as well
